services:
  - type: web
    name: yeabneh-store
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: yeabneh-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: LOG_CHANNEL
        value: stack

databases:
  - name: yeabneh-db
    plan: free
    databaseName: yeabnehs_store
